/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2f6c1c5d-bd0b-4b35-be75-09a1cbfaa52a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5Lzhrv4Z8", // to change user pools
    "aws_user_pools_web_client_id": "3voc2kliuoc6jok8ienqrr2t2t",
    "oauth": {}
};


export default awsmobile;
